server.port=${PORT:8080}

spring.datasource.url=jdbc:postgresql://${DB_HOST}:${DB_PORT:5432}/${DB_NAME}?sslmode=${DB_SSLMODE:prefer}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}


security.jwt.secret=${JWT_SECRET}

security.jwt.issuer=${JWT_ISSUER:buildtrack-api}
security.jwt.expiration-seconds=${JWT_EXPIRATION_SECONDS:3600}