spring.application.name=buildtrack

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.open-in-view=false

spring.flyway.enabled=true

security.jwt.issuer=${JWT_ISSUER:buildtrack-api}
security.jwt.expiration-seconds=${JWT_EXPIRATION_SECONDS:3600}


management.endpoints.web.exposure.include=health
management.endpoint.health.show-details=never