ALTER TABLE builds
    ADD COLUMN completed_at TIMESTAMP WITH TIME ZONE;

ALTER TABLE issues
    ADD COLUMN resolved_at TIMESTAMP WITH TIME ZONE;

ALTER TABLE releases
    ADD COLUMN published_at TIMESTAMP WITH TIME ZONE;